import { defineConfig } from 'vite'
import path from 'path'
import fs from 'fs'
import tailwindcss from '@tailwindcss/vite'
import react from '@vitejs/plugin-react'

const GENERATED_ASSET_MODULE_PATH = path.resolve(__dirname, 'src/generated/live-assets.ts')


function figmaAssetResolver() {
  return {
    name: 'figma-asset-resolver',
    resolveId(id) {
      if (id.startsWith('figma:asset/')) {
        const filename = id.replace('figma:asset/', '')
        return path.resolve(__dirname, 'src/assets', filename)
      }
    },
  }
}

function liveAssetList() {
  const supportedExtensions = new Set(['.jpg', '.jpeg', '.png', '.webp', '.gif', '.svg'])
  const assetRoots = {
    herosection: path.resolve(__dirname, 'public/assets/herosection'),
    gallery: path.resolve(__dirname, 'public/assets/gallery'),
  }

  const walk = (dir: string): string[] => {
    if (!fs.existsSync(dir)) return []
    const entries = fs.readdirSync(dir, { withFileTypes: true })
    const files: string[] = []

    for (const entry of entries) {
      const fullPath = path.join(dir, entry.name)
      if (entry.isDirectory()) {
        files.push(...walk(fullPath))
        continue
      }

      if (entry.isFile() && supportedExtensions.has(path.extname(entry.name).toLowerCase())) {
        const relativePath = path.relative(path.resolve(__dirname, 'public'), fullPath).split(path.sep).join('/')
        files.push(`/${relativePath}`)
      }
    }

    return files.sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))
  }

  const writeGeneratedModule = () => {
    const heroImages = walk(assetRoots.herosection)
    const galleryImages = walk(assetRoots.gallery)

    const moduleContent = [
      '// Generated by vite.config.ts - do not edit',
      '',
      `export const heroImages = ${JSON.stringify(heroImages, null, 2)};`,
      '',
      `export const galleryImages = ${JSON.stringify(galleryImages, null, 2)};`,
      '',
    ].join('\n')

    fs.mkdirSync(path.dirname(GENERATED_ASSET_MODULE_PATH), { recursive: true })
    fs.writeFileSync(GENERATED_ASSET_MODULE_PATH, moduleContent)
  }

  return {
    name: 'live-asset-list',
    buildStart() {
      writeGeneratedModule()
    },
    configureServer(server: any) {
      writeGeneratedModule()

      const notify = (filePath: string) => {
        const normalized = filePath.split(path.sep).join('/')
        const assetRoot = normalized.includes('/public/assets/herosection/')
          ? 'herosection'
          : normalized.includes('/public/assets/gallery/')
            ? 'gallery'
            : null

        if (assetRoot) {
          writeGeneratedModule()
          server.ws.send({ type: 'full-reload' })
        }
      }

      server.watcher.on('add', notify)
      server.watcher.on('unlink', notify)
      server.watcher.on('change', notify)

    },
  }
}

export default defineConfig({
  plugins: [
    figmaAssetResolver(),
    liveAssetList(),
    // The React and Tailwind plugins are both required for Make, even if
    // Tailwind is not being actively used – do not remove them
    react(),
    tailwindcss(),
  ],
  resolve: {
    alias: {
      // Alias @ to the src directory
      '@': path.resolve(__dirname, './src'),
    },
  },

  // File types to support raw imports. Never add .css, .tsx, or .ts files to this.
  assetsInclude: ['**/*.svg', '**/*.csv'],
})
